# Generated by Django 3.1.7 on 2021-02-20 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='reciever',
        ),
        migrations.AddField(
            model_name='relationship',
            name='receiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='profiles.profile'),
        ),
    ]
